name: Trigger Playwright Test

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  trigger-playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Playwright Workflow in Another Repo
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          https://api.github.com/repos/RTP-OTS/playwright/actions/workflows/automate-test.yml/dispatches \
          -d '{"ref":"main"}'
