name: Trigger and Wait Playwright Tests

on:
  pull_request:
    branches: [main, develop]

jobs:
  trigger_and_wait_playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Playwright Tests
        uses: convictional/trigger-workflow-and-wait@v1.6.2
        with:
          owner: RTP-OTS
          repo: playwright
          github_token: ${{ secrets.PAT_TOKEN }}
          workflow_file_name: automate-test.yml
          ref: main
          wait_interval: 30
          propagate_failure: true
